# Site settings
title: BigFish Blog
description: The journey to become a BIG FISH
url: "https://mayoflayo.github.io" # Your GitHub Pages URL

# Theme settings
theme: minima # Replace 'minima' with the Jekyll theme you'd like to use

# Other settings
plugins:
  - jekyll-feed
